language: node_js
node_js:
- '12'
sudo: false
git:
  depth: 1
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint
- npm run test
- npm run build
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: cbfgVMohNsTkyiPR1woMwlpuktSIrmEd0bcq/nzo44FWjfHPrsSmLn/ozJiREAF3lUKGMFKLmwu7rNwv4fQ7OyeC5GC2pBDOeN7XoWrAdn7VvyKP1pzByOrupokHf16wzYAqcN09wqpaiXR+/3oNVoAd0Uxe+FPFm/iNLwTUkuqWkxkxsBqZ8l/OA/LB4ao+XlX7rb6S5lKwd9FdEV80UhlHRkaBtyEzm+HpZSyWHWGbiDMVJO4yQ8HLpAX1cHxjT0c4pKNUJmHRFbxVU9seghBurCiUb78mRnRfAprGZBhQH0RYnKSkvWJxU3WgXVphmU/BVO/9QPSJTT3rGiQLmd+0kkwLU8sremLiStKRGx3rxiP8/93aujAW+IcFkXFqJB9kPmMg4rAiWh9F2N2T/WhkyaevTn7DCZf+s+EuU4J9IS1GtpPPbRFmJ5gR6Y72pZDxD9LODkB2jS1KIxQqcX4pgBjvnTZQeuY2RQwAXjTZ8ZCpRdkKPtDwEWGhnhQ4useNw/MQNNRa9WZmsXSNV8598lAqLWgLhKObF+ZoY856bXz2W5yU2tLN6ABB3HbrurfM/5Zb1aDx+6YGgVL0QCUuCG06UBOf0efRf2rLJ2Bt1m4EbviJDT8DvqiVJJkNquITFLzFNdiuMTr8WDvT3E/MFkjAZIGMRDP9qsuRlmM=
  - secure: jjjsOAYBkMRE3sQToF2mEneyisrZzS5qdT4aWAoe69AVlY3wdPk50fggk5jZ8m4OGRoqKZuRDwyDaXat4mClgQH6nlySLPK9S7qKjL2dkmJyYaL75cyX+ABLTozKOgwq7SQUypTQcsg0y8crAdHHPmYmFZ6waMDQ/Wc3y6spPqSJVK/GSggxcpLKb/Xc7/iV9RZA7joq8rKsPX/TZWSGjtyJEHKo7tx3RdJHS8XGkfr+zw1Pr4/IGEpSI1T65kvaZCXpWPJPvA4nBC5YO1oMpNkQBVCG8fN2gcP2heGLiqvNbQThGhzOMMMBPWGgf1rnI6wY8kGQcAVMQdpYmYGpC3amJFQAt/8zS0ss5eh27TcJCyZFvo2BrOF/ryfIiaVzp2eh4rzSlmMaZ/iYzE2UG9zuvQomJpLJenMxPpBqT0QJ8IwoR+JXSnEfNZPhmBv8/Loi8huU01E/X1P9JLMxv81PqPTSfubYU+MXSwhzemcSCW3azxwKyCqePiBUSBDy27bT5azbN0nb4q9KTSCNbG0dVzKfFJK2QEupAos0gvtb7hLMOr79SQGj3jfEsAW1P16o27AKmQ1x5MOZCVgVzophY6+1F9I0HbyZx9PcVMldTRLZGwZhlUITLRpphLSdn6DgBKo5FbarBrvpNmGOWxtlYb7Vxt0Q2SdSMCqBF7k=
